# Intro to Python  
1. Python Basics
2. Python Lists
3. Functions and Packages
4. NumPy

### 1. Python Basics

In [ ]:
# TBD

### 2. Python Lists  
`[a, b, c]`  
`[1.42, 1,78, 1,55]`  
`fam = [1.42, 1,78, 1,55]`  
A list is a way to give
* Name to a collection of values
* Contain any type
* Contain different types (also list of list)  
* Specific functionality
* Specific behavior

In [1]:
team2 = [["erkki", 1.68],
         ["petr", 1.76],
         ["martti", 1.75],
         ["sven", 183]]
team2

[['erkki', 1.68], ['petr', 1.76], ['martti', 1.75], ['sven', 183]]

In [2]:
type(team2)

list

**Create a list**  
* Create a list, areas, that contains the area of the hallway (`hall`), kitchen (`kit`), living room (`liv`), bedroom (`bed`) and bathroom (`bath`), in this order. Use the predefined variables.
* Print `areas` with the `print()` function.

In [3]:
# area variable (ln square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall,kit,liv,bed,bath]

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


* Finish the code that creates the `areas` list. Build the list so that the list first contains the name of each room as a string and then its area. In other words, add the strings `"hallway"`, `"kitchen"` and `"bedroom"` at the appropriate locations.
* Print `areas` again; is the printout more informative this time?

In [5]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


* Finish the list of lists so that it also contains the bedroom and bathroom data. Make sure you enter these in order!
* Print out `house`; does this way of structuring your data make more sense?
* Print out the type of `house`. Are you still dealing with a list?

In [6]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]

# Print out house
print(house)

# Print out the type of house
print(type(house))

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


**Subsetting Lists**  
First index of a list is 0. Called 0-indexing. 
  
Selecting the third element using index two.

In [9]:
names = ["al","bea","dorf","zoe","ruy"]
names[2]

'dorf'

In [10]:
names[-1] # last index

'ruy'

**List slicing**  
By specifying a range we can slice a list and create a new list.  
`[start : end]`  
inclusive exclusive  

`mylist[begin:end]`

In [17]:
names[3:5] # only the elements of index 3,4 is returned

['zoe', 'ruy']

In [19]:
names[:3] # leave out the index where it should start, the output starts at 0

['al', 'bea', 'dorf']

In [20]:
names[3:] # Leave out the index where it should end, the output starts from 3 index until end

['zoe', 'ruy']

* Print out the second element from the `areas` list (it has the value `11.25`).
* Subset and print out the last element of `areas`, being `9.50`. Using a negative index makes sense here!
* Select the number representing the area of the living room (`20.0`) and print it out.  
  
* Using a combination of list subsetting and variable assignment, create a new variable, `eat_sleep_area`, that contains the sum of the area of the kitchen and the area of the bedroom.
* Print the new variable `eat_sleep_area`.

In [22]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3] + areas[7]

# Print the variable eat_sleep_area
print(eat_sleep_area)

11.25
9.5
20.0
28.75


* Use slicing to create a list, `downstairs`, that contains the first 6 elements of `areas`.
* Do a similar thing to create a new variable, `upstairs`, that contains the last 4 elements of `areas`.
* Print both `downstairs` and `upstairs` using `print()`.

In [23]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[:6]

# Use slicing to create upstairs
upstairs = areas[-4:]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


**Subsetting list of lists**  
To subset lists of lists, you can use the same technique as before: square brackets.  
What will `house[-1][1]` return?

In [28]:
house

[['hallway', 11.25],
 ['kitchen', 18.0],
 ['living room', 20.0],
 ['bedroom', 10.75],
 ['bathroom', 9.5]]

In [29]:
house[-1][1]

9.5

**Manipulating Lists**  
* Change elements from lists  
`house[2] = ['toilet',2.5]`  
* Add list elements  
`house_ext = house + ['pool',45]`  
* Remove list elements  
`del(house[2])`  
  
Behind the scenes  
`x = ["a", "b", "c"]`  
`y = x`   
`y[1] = 'z'`  
`x` list points to the `y` list in the memory, for efficient memory allocation.  
You need to do the following to create a separate list (stored in separate memory):  
`y = x[:]`  

In [30]:
x = ["a", "b", "c", "d"]
x[1] = "r"
x[2:] = ["s", "t"]

In [31]:
x

['a', 'r', 's', 't']

In [35]:
x = ["a", "b", "c", "d"]
y = x + ["e", "f"]
y

['a', 'b', 'c', 'd', 'e', 'f']

* Update the area of the bathroom area to be 10.50 square meters instead of 9.50.
* Make the `areas` list more trendy! Change `"living room"` to `"chill zone"`.  
  
* Use the `+` operator to paste the list `["poolhouse", 24.5]` to the end of the `areas` list. Store the resulting list as `areas_1`.
* Further extend `areas_1` by adding data on your garage. Add the string `"garage"` and float `15.45`. Name the resulting list `areas_2`.

In [36]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[9] = 10.50

# Change "living room" to "chill zone"
areas[4] = "chill zone"

print(areas)

# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage"] + [15.45]

print(areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


**Delete list elements**  
We can remove elements from the list using `del` statement:

In [37]:
x = ["a", "b", "c", "d"]
del(x[1])
x

['a', 'c', 'd']

In [43]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]
print(areas)
del(areas[-4:-2])
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 15.45]


In [42]:
areas[-4:-2]

['poolhouse', 24.5]

**Inner workings of lists**

In [45]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = areas

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)


# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = areas[:]
#areas_copy = list(areas) # alternative way

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)

# The difference between explicit and reference-based copies is subtle, 
# but can be really important. Try to keep in mind how a list is stored in the computer's memory.

[5.0, 18.0, 20.0, 10.75, 9.5]
[11.25, 18.0, 20.0, 10.75, 9.5]


### 3. Functions and Packages  
* Nothing new
* `type()`, `round()`
* Piece of resuable code
* Solves particular task
* Call function instead of writing code yourself

In [46]:
help(round) # open up help about round() function

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



**Familiar functions**  
* Use `print()` in combination with `type()` to print out the type of `var1`.
* Use `len()` to get the length of the list `var1`. Wrap it in a `print()` call to directly print it out.
* Use `int()` to convert `var2` to an integer. Store the output as `out2`.

In [48]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

# Print out length of var1
print(len(var1))

# Convert var2 to an integer: out2
out2 = int(var2)
type(out2)

<class 'list'>
4


int

In [51]:
#help(complex)
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



**Multiple arguments**  
You'll see that `sorted()` takes three arguments: `iterable`, `key` and `reverse`.

`key=None` means that if you don't specify the `key` argument, it will be `None`. `reverse=False` means that if you don't specify the `reverse` argument, it will be `False`.  
  
* Use `+` to merge the contents of `first` and `second` into a new list: `full`.
* Call `sorted()` on `full` and specify the `reverse` argument to be `True`. Save the sorted list as `full_sorted`.
* Finish off by printing out `full_sorted`.

In [52]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse=True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


**Methods**  
Built-in Functions are only one part of the story  
* `max()`,`len()`  
* Get index in list: ?
* Reversing a list: ?  
You can look for built in functions that do the latter two but you wont find them.  
  
Python objects such as `str`, `float`, `list` also come with a bunch of methods.  
  
* Methods: Functions that belong to objects.  
Object of `str` type have example methods suchs as `capitalize()`,`replace()`  
Object of `list` type have example methods suchs as `index()`,`count()` 
* Methods: call functions on object with the dot notation `list.index("asd")`

In [56]:
full_sorted.index(10.75) # Call method index() on list (to get the index of 10.75 from list)

3

In [57]:
full_sorted.count(10.75) # Call method count() on list to see how many times 10.75 occurs in list

1

In [59]:
sister = 'lisa'
sister.capitalize() # Call method capitalize() on str to make first letter in string capital

'Lisa'

In [60]:
sister.replace("s","z") # Call method replace() on str to replace s with z

'liza'

* Everything = object
* Object have methods associated, depending on type
Objects can have the same name method.  
* Some methods change the object they are called on like `append()` on a list

In [64]:
print(sister.index("s")) # index of the letter in the string
print(full_sorted.index(10.75)) # index of the element in the list

2
3


In [65]:
full_sorted.append(17.2) # adds one element to the list

In [66]:
full_sorted

[20.0, 18.0, 11.25, 10.75, 9.5, 17.2]

**String Methods**
Strings come with a bunch of methods. Lets diiscover some of them. If we want to discover them in more detail, type `help(str)`  
  
* Use the `upper()` method on `place` and store the result in `place_up`. Use the syntax for calling methods that you learned in the previous video.
* Print out `place` and `place_up`. Did both change?
* Print out the number of o's on the variable `place` by calling `count()` on `place` and passing the letter `'o'` as an input to the method. We're talking about the variable place, not the word "place"!

In [2]:
#help(str)

In [3]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up
place_up = place.upper()

# Print out place and place_up
print(place)
print(place_up)

# Print out the number of o's in place
print(place.count('o'))

# Notice that the upper() method does not change the object that it is called on.

poolhouse
POOLHOUSE


3

**List Methods**  
Strings are not the only Python types that have methods associated with them. `Lists`, `floats`, `integers` and `booleans` are also types that come packaged with a bunch of useful methods. We will experimenting with:

* `index()`, to get the index of the first element of a list that matches its input and
* `count()`, to get the number of times an element appears in a list.  
  
Instructions:  
* Use the `index()` method to get the index of the element in areas that is equal to 20.0. Print out this index.
* Call `count()` on areas to find out how many times 9.50 appears in the list. Again, simply print out this number.  
  
These are examples of list methods that *do not change* the list they are called upon.

In [4]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 9.50 appears in areas
print(areas.count(9.50))

2
1


Most list methods *will change* the list they're called on. Examples are:

* `append()`, that adds an element to the list it is called on,
* `remove()`, that removes the first element of a list that matches the input, and
* `reverse()`, that reverses the order of the elements in the list it is called on.  
  
Instructions:  
* Use `append()` twice to add the size of the poolhouse and the garage again: 24.5 and 15.45, respectively. Make sure to add them in this order.
* Print out areas
* Use the `reverse()` method to reverse the order of the elements in areas.
* Print out areas once more.

In [5]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


**Packages**  
Maintaining all functions would be huge, this is were packages come into play.  
  
* Directory of Python Scripts
* Each scipt is a so called module
* Specify functions, methods, types
* Thousands of packages available
 * Numpy
 * Matplotlib
 * Scikit-learn  
  
To use some of the packages we first need to install package  
* https://pip.pypa.io/en/stable/installing/
* Download `get-pip.py`
* Terminal:
 * `python3 get-pip.py`
 * `pip3 install numpy`
  
**Import package**  
  
`import numpy`
 

In [7]:
# import all functions from numpy
import numpy as np
np.array([1, 2, 3])  # This is preferred, clearly using numpy

# import only array function from numpy
from numpy import array
array([1, 2, 3])

array([1, 2, 3])

Import package
Some geometry basics. 

For a fancy clustering algorithm, you want to find the circumference, , and area, , of a circle. When the radius of the circle is `r`, you can calculate C = `2*r*pi` and A = `pi*r^2`.  


To use the constant `pi`, you'll need the `math` package. A variable `r` is already coded in the script. Fill in the code to calculate `C` and `A` and see how the `print()` functions create some nice printouts.  
  
Instructions:  
* Import the `math` package. Now you can access the constant `pi` with `math.pi`.
* Calculate the circumference of the circle and store it in `C`.
* Calculate the area of the circle and store it in `A`.

In [9]:
# Definition of radius
r = 0.43

# Import the math package
import math as math

# Calculate C
C = 2*math.pi*r

# Calculate A
A = math.pi*r**2

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


**Selective import**  
General imports, like `import math`, make all functionality from the `math` package available to you. However, if you decide to only use a specific part of a package, you can always make your import more selective:

`from math import pi`  

Let's say the Moon's orbit around planet Earth is a perfect circle, with a radius `r` (in km) that is defined in the script.  
  
Instructions:  
* Perform a selective import from the `math` package where you only import the `radians` function.
* Calculate the distance travelled by the Moon over 12 degrees of its orbit. Assign the result to `dist`. You can calculate this as `r * phi`, where `r` is the radius and `phi` is the angle in radians. To convert an angle in degrees to an angle in radians, use the `radians()` function, which you just imported.
* Print out `dist`.

In [1]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
dist = r * radians(12)

# Print out dist
print(dist)

40317.10572106901


In [2]:
help(radians)

Help on built-in function radians in module math:

radians(x, /)
    Convert angle x from degrees to radians.



### 3. Numpy 
**List Recap**
* Powerful
* Collection values
* Can hold different types
* Change, add, remove
* Need for Data Science
 * Mathematical operations over collections
 * Speed is necessary, with list this is a problem!
 * Python cannot do calculations on lists, it will give you an error. You could solve this by going over each element but that is very inefficient!
 * Soluiton: Numpy Array
   
**Numpy**
* Numeric Python
* Alternative to Python List: Numpy array
* Calculations over entire arrays
* Numpy knows how to work with arrays as if they were single elements
* Easy and Fast!


In [3]:
# Illustration of List calculation error
height = [1.75, 1.68, 1.71, 1.79]
weight = [65.4, 59.2, 63.4, 82.8]
print(height)
print(weight)

[1.75, 1.68, 1.71, 1.79]
[65.4, 59.2, 63.4, 82.8]


In [4]:
# Python cannot do calculations on lists 
bmi = height / weight **2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [5]:
# using numpy
import numpy as np

# Creating numpy arrays using list as input
np_height = np.array(height)
np_height
np_weight = np.array(weight)
np_weight

# calculations works and is fast with numpy
bmi = np_weight / np_height ** 2
bmi

# the bmi is calculated elementwise, by dividing the np_weight with squared np_height

array([21.35510204, 20.97505669, 21.68188502, 25.84189008])

**Numpy: remarks**  
* Numpy arrays: contain only one type
* If you try to create np array with different types it will contain only one type (string for example)
* Numpy arrays come with their own methods
* Different type behave differently!

In [18]:
# The float and the boolean are both converted to strings
np.array([1.0, "is", True])

array(['1.0', 'is', 'True'], dtype='<U32')

In [10]:
# compare list method vs array method
python_list = [11, 12, 13]
numpy_array = np.array([11, 12, 13])

# adding python lists together, the list elements are pasted together
print(f'Adding python lists together: {python_list + python_list}')

# adding np arrays, element wise sum is done
print(f'Adding np arrays together: {numpy_array + numpy_array}')

Adding python lists together: [11, 12, 13, 11, 12, 13]
Adding np arrays together: [22 24 26]


**Numpy Subsetting**  
* You can use pretty much the same squared brackets with arrays as lists
* In numpy you can also use an array of booleans

In [11]:
bmi

# bracket subsetting to get second element of array
print(bmi[1])

# get all bmi values that are over 23
print(bmi > 23)
# this results in a numpy array with False if element < 23, True if >

# Next, we can use this boolean array in brackets to do the subsetting
bmi[bmi > 23]
# Only the elements > 23, i.e which bolean value is True, is selected
# Gives an np array with that one element

20.97505668934241
[False False False  True]


array([25.84189008])

In [33]:
# Create a simple numpy array

# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


**Baseball players´ height**  

Instructions:  
* Create a `numpy` array from `height_in`. Name this new array `np_height_in`.
* Print `np_height_in`.
* Multiply `np_height_in` with `0.0254` to convert all height measurements from inches to meters. Store the new values in a new array, `np_height_m`.
* Print out np_`height_m` and check if the output makes sense.

In [13]:
# Create height_in list, containing height in inches
height_in = [74,75,68,69,73]

# Import numpy
import numpy as np

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)

# n the blink of an eye, numpy performs multiplications!

[74 75 68 69 73]
[1.8796 1.905  1.7272 1.7526 1.8542]


**Baseball Players´ BMI**  
  
Instructions:  
* Create a `numpy` array from the `weight_lb` list with the correct units. Multiply by `0.453592` to go from pounds to kilograms. Store the resulting `numpy` array as `np_weight_kg`.
* Use `np_height_m` and `np_weight_kg` to calculate the BMI of each player. Use the following equation: BMI = ( weight(kg) / height(m)^2 ) Save the resulting numpy array as bmi.
* print `bmi`

In [14]:
# Create weight_lb list, containing weight in pounds
weight_lb = [212,187,208,192,204]

# Import numpy
import numpy as np

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg / np_height_m**2

# Print out bmi
print(bmi)

[27.21888775 23.37313852 31.62594145 28.35312942 26.91425732]


**Lightweight baseball players**  
To subset both regular Python lists and numpy arrays, you can use square brackets:

`x = [4 , 9 , 6, 3, 1]`  
`x[1]`  
`import numpy as np`  
`y = np.array(x)`  
`y[1]`  
For `numpy` specifically, we can also use boolean `numpy` arrays:  
`high = y > 5`  
`y[high]`  
  
Instructions:  
* Create a boolean `numpy` array: the element of the array should be `True` if the corresponding baseball player's BMI is below 21. You can use the `<` operator for this. Name the array `light`.
* Print the array `light`.
* Print out a `numpy` array with the BMIs of all baseball players whose BMI is below 27. Use `light` inside square brackets to do a selection on the `bmi` array.

In [15]:
# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array (bmi < 27)
light = bmi < 27

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[False  True False False  True]
[23.37313852 26.91425732]


**NumPy Side Effects**  
As said before, `numpy` is great for doing vector arithmetic. If you compare its functionality with regular Python lists, however, some things have changed.

First of all, `numpy` arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as type coercion.

Second, the typical arithmetic operators, such as `+`, `-`, `*` and `/` have a different meaning for regular Python lists and `numpy` arrays.

Have a look at this line of code:

Can you tell which code chunk builds the exact same Python object? The numpy package is already imported as np, so you can start experimenting in the IPython Shell straight away!

In [39]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

Can you tell which code chunk builds the exact same Python object? The numpy package is already imported as np, so you can start experimenting in the IPython Shell straight away!  
  
Possible answers*  
* A `np.array([True, 1, 2, 3, 4, False])`
* B `np.array([4, 3, 0]) + np.array([0, 2, 2])`
* C `np.array([1, 1, 2]) + np.array([3, 4, -1])`
* D `np.array([0, 1, 2, 3, 4, 5])`

In [40]:
# B
np.array([4, 3, 0]) + np.array([0, 2, 2])

array([4, 5, 2])

True is converted to 1, False is converted to 0.

**Subsetting NumPy Arrays**  
You've seen it with your own eyes: Python lists and numpy arrays sometimes behave differently. Luckily, there are still certainties in this world. For example, subsetting (using the square bracket notation on lists or arrays) works exactly the same. To see this for yourself, try the following lines of code in the IPython Shell:

`x = ["a", "b", "c"]`  
`x[1]`  
  
`np_x = np.array(x)`  
`np_x[1]`  

Instructions:  
* Subset `np_weight_lb` by printing out the element at index 3.
* Print out a sub-array of `np_height_in` that contains the elements at index 2 up to and including index 3.

In [16]:
# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 3
print(np_weight_lb[3])

# Print out sub-array of np_height_in: index 2 up to and including index 3
print(np_height_in[2:4])

192
[68 69]


**2D Numpy Arrays**  
If we check the `type` of the arrays we have created python tells us they are `numpy.ndarray`, this is a n-dimensional array. The arrays created before are one dimensional arrays. We can also create 2, 3, ... n dimensional arrays.  
  
We create one 2D array for all `weight` and `height data`. 

In [17]:
np_2d = np.array([[1.86, 1.75, 1.58, 1.82, 1.73],
                  [79.2, 82.1, 73.7, 77.4, 68.8]])
np_2d

array([[ 1.86,  1.75,  1.58,  1.82,  1.73],
       [79.2 , 82.1 , 73.7 , 77.4 , 68.8 ]])

We see that `np_2d` is a regular data structure each sub-list in a list corresponds to a row in the 2d array. We can check with `shape` attribute to get more info about the data structure, number of rows and columns. Attributes do not have `()` like methods, they are not the same.

In [20]:
np_2d.shape # 2 rows, 5 cols

(2, 5)

The type of 2d arrays also must be same type. If we change one element to string, all elements will be coerced to string so we have a homogenuous array.

In [21]:
np.array([['1.86', 1.75, 1.58, 1.82, 1.73],
          [79.2, 82.1, 73.7, 77.4, 68.8]])

array([['1.86', '1.75', '1.58', '1.82', '1.73'],
       ['79.2', '82.1', '73.7', '77.4', '68.8']], dtype='<U4')

The 2d array is like a list of lists and we can do more advanced sub-setting. If we want the first row and third element of the array:

In [26]:
# alt 1 of sub-settings
print(np_2d[0][2])

# alt 2 of sub-setting, using single squared brackets and a comma
print(np_2d[0,2])

# both alternatives returns the intersection of rows and columns

1.58
1.58


Let´s say we want to have the length and weight of the second and third family member. We want both rows, so we put in a colon `:` before the comman `,` and put in the indices 1 to 3 `1:3` after the comma. The intersection of the seleciton gives as a 2d array of 2 rows and 2 columns.

In [28]:
np_2d[:, 1:3]

array([[ 1.75,  1.58],
       [82.1 , 73.7 ]])

Similarily we can select only the weight of all family members. So we put `1` before the comma, we want all columns so we use a colon `:` after the comma. The intersection gives us the whole second row.

In [29]:
np_2d[1,:]

array([79.2, 82.1, 73.7, 77.4, 68.8])

2d arrays gives us the possibility to do element wise calculations just like we did with 1d arrays.

**Create 2D numpy array**  
  
Instructions:  
* Use `np.array()` to create a 2D `numpy` array from `baseball`. Name it np_baseball.
* Print out the type of `np_baseball`.
* Print out the `shape` attribute of `np_baseball`. Use `np_baseball.shape`.

In [74]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

# Check out the array of lenght and weight
np_baseball

<class 'numpy.ndarray'>
(4, 2)


array([[180. ,  78.4],
       [215. , 102.7],
       [210. ,  98.5],
       [188. ,  75.2]])

**Subsetting 2d numpy arrays**  
If your 2D `numpy` array has a regular structure, i.e. each row and column has a fixed number of values, complicated ways of subsetting become very easy. Have a look at the code below where the elements `"a"` and `"c"` are extracted from a list of lists.

In [32]:
# regular list of lists
x = [["a", "b"], ["c", "d"]]
[x[0][0], x[1][0]]

# numpy
import numpy as np
np_x = np.array(x)
np_x[:,0]

array(['a', 'c'], dtype='<U1')

For regular Python lists, this is a real pain. For 2D `numpy` arrays, however, it's pretty intuitive! The indexes before the comma refer to the rows, while those after the comma refer to the columns. The `:` is for slicing; in this example, it tells Python to include all rows.  
  
Instructions:  
* Print out the 3rd row of `np_baseball`.
* Make a new variable, `np_weight_lb`, containing the entire second column of `np_baseball`.
* Select the (first column) of the 124th baseball player in `np_baseball` and print it out.

In [76]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 3th row of np_baseball
print(np_baseball[3,:])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]

# Print out height of 2nd player
print(np_baseball[2,0])

[188.   75.2]
210.0


**2D array arithmetics**  
Remember how you calculated the Body Mass Index for all baseball players? `numpy` was able to perform all calculations element-wise (i.e. element by element). For 2D `numpy` arrays this isn't any different! You can combine matrices with single numbers, with vectors, and with other matrices:

In [61]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
print(f'''Multiply array with constant of 2 gives: 
{np_mat * 2}''')
print(f'''Adding array with another array of 1 row, 1 col gives: 
{np_mat + np.array([10, 10])}''')
print(f'''Adding the array with itself gives: 
{np_mat + np_mat}''')

Multiply array with constant of 2 gives: 
[[ 2  4]
 [ 6  8]
 [10 12]]
Adding array with another array of 1 row, 1 col gives: 
[[11 12]
 [13 14]
 [15 16]]
Adding the array with itself gives: 
[[ 2  4]
 [ 6  8]
 [10 12]]


Instructions:
* We want to convert the units of height and weight to metric (meters and kilograms respectively). As a first step, create a `numpy` array with three values: `0.0254`, `0.453592`. Name this array conversion.
* Multiply `np_baseball` with `conversion` and print out the result.

In [1]:
# Import numpy package
import numpy as np

# Create baseball, a list of lists (with two columns: height, weight)
baseball = [[180, 78.4],
            [215, 79.7],
            [210, 80.1],
            [188, 75.2]]

# Create height_in list, containing height in inches and weight_lb, weight in pounds
np_baseball = np.array(baseball)
print(np_baseball)

# Create numpy array: conversion for height_in, weight_lb
conversion = np.array([0.453592, 0.0254])

# print before conversion
print(np_baseball)

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[180.   78.4]
 [215.   79.7]
 [210.   80.1]
 [188.   75.2]]
[[180.   78.4]
 [215.   79.7]
 [210.   80.1]
 [188.   75.2]]
[[81.64656   1.99136 ]
 [97.52228   2.02438 ]
 [95.25432   2.03454 ]
 [85.275296  1.91008 ]]


Notice how with very little code, you can change all values in your `numpy` data structure in a very specific way. This will be very useful as a data scientist.  
  
**Numpy Basic Statistics**  
  
Data analysis  
* Get to know your data
* Use Summary statistics using Numpy
 * `np.mean()`
 * `np.median()`
 * `np.std()`
 * `np.corrcoef()`
 * `np.sum()`
 * `np.sort()`
* These functions exists in the basic Python distribution also, but when using `numpy` it enforce single data type which makes the big difference in calculation speed! 

In [2]:
# sub-set first to get the height column from the 2D array and then find the mean height
np.mean(np_baseball[:,0])

198.25

In [3]:
np.median(np_baseball[:,0])

199.0

In [4]:
# Check correlation coeff between height and weight
np.corrcoef(np_baseball[:,0], np_baseball[:,1])

array([[1.        , 0.66182484],
       [0.66182484, 1.        ]])

**Generate data**  
  
We can simulate new data easily using `numpy`.
* Arguments for `np.random.normal()`
 * distribution mean
 * distribution standard deviation
 * number of samples  

* Then use `np.column_stack(())` to paste them together as two columns.

In [19]:
height = np.round(np.random.normal(1.76, 0.21, 100), 2)

weight = np.round(np.random.normal(63.5, 14, 100), 2)

print(height[0:5])
print(weight[0:5])

height_weight_np = np.column_stack((height,weight))
print(height_weight_np[0:5,:])
height_weight_np.shape

[1.95 1.71 1.4  1.59 1.5 ]
[61.77 66.83 68.94 52.01 62.3 ]
[[ 1.95 61.77]
 [ 1.71 66.83]
 [ 1.4  68.94]
 [ 1.59 52.01]
 [ 1.5  62.3 ]]


(100, 2)

**Average vs Median and Correlation**  
Instructions:  
* Create numpy array `np_height` that is equal to first column of `height_weight_np`.
* Print out the mean of `np_height_in`.
* Print out the median of `np_height_in`.
* Check the correlation between height and weight of `height_weight_np`

In [20]:
# create np_height from height_weight_np
np_height = height_weight_np[:,0]

# print out the mean of np_height
print(np.mean(np_height))

# print out the median of np_height
print(np.median(np_height))

# print out the correlation between first and second column
print(np.corrcoef(height_weight_np[:,0], height_weight_np[:,1]))

1.7238
1.73
[[ 1.         -0.07613378]
 [-0.07613378  1.        ]]


**Blending it together**  
  
Use some soccer data instead of baseball to blend all the things we learned together.  
  
Instrucitons:  
* Create `heights` and `positions` lists.
* Convert `heights` and `positions`, which are regular lists, to numpy arrays. Call them `np_heights` and `np_positions`.
* Extract all the heights of the goalkeepers. You can use a little trick here: use `np_positions == 'GK'` as an index for `np_heights`. Assign the result to `gk_heights`.
* Extract all the heights of all the other players. This time use `np_positions != 'GK'` as an index for `np_heights`. Assign the result to `other_heights`.
* Print out the median height of the goalkeepers using `np.median()`.
* Do the same for the other players. Print out their median height. Replace None with the correct code.


In [21]:
# create heights and positions lists
heights = [191, 184, 185, 180, 181, 187, 170, 179, 183, 186, 185, 170, 187, 183, 173, 188, 183, 180, 188, 175, 
 193, 180, 185, 170, 183, 173, 185, 185, 168, 190, 178, 185, 185, 193, 183, 184, 178, 180, 177, 188,
 177, 187, 186, 183, 189, 179, 196, 190, 189, 188, 188, 188, 182, 185, 184, 178, 185, 193, 188, 179]

positions = ['GK', 'M', 'A', 'D', 'M', 'D', 'M', 'M', 'M', 'A', 'M', 'M', 'A', 'A', 'A', 'M', 'D', 'A', 'D', 'M',
 'GK', 'D', 'D', 'M', 'M', 'M', 'M', 'D', 'M', 'GK', 'D', 'GK', 'D', 'D', 'M', 'A', 'M', 'D', 'M', 'GK',
 'M', 'GK', 'A', 'D', 'GK','GK', 'M', 'A', 'D', 'M', 'D', 'M', 'M', 'M', 'A', 'M', 'M', 'A', 'M', 'GK']

# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)

# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

Median height of goalkeepers: 188.0
Median height of other players: 184.0


When comparing these medians goal keepers seem to be taller than other players.  
End of course. Next suggested course is:  Basic plots with Matplotlib.